#!/usr/bin/php
<?php
if(php_sapi_name() !== 'cli'){
	exit;
}
require __DIR__. '/vendor/autoload.php';

use Boilcli\App;

$app = new App();

$app->registerController('helloc', new \App\Command\HelloController($app));

$app->registerCommand('hello', function ($argv) use ($app){
	$name = isset( $argv[2] ) ? $argv[2] : "world";
	$app->getPrinter()->out("hello $name !!!!!!!!");
});

$app->runCommand($argv);
